name: 'API Integration - Github Actions Terraform'
description: 'Communicate with Github Actions and Terraform Cloud'
author: 'Monabele'
inputs:
  tf_api_token:
    description: 'Terraform Cloud API Token'
    required: true
  tf_workspace:
    description: 'Terraform Cloud Workspace'
    required: true
  tf_organization:
    description: 'Terraform Cloud Organization'
    required: true
  tf_run_type:
    description: 'Terraform Cloud Run Type'
    required: true

# Workspace Variables API
  variable_type:
    description: 'Workspace Variable Type'
    required: false
    default: 'var'
  variable_key:
    description: 'Workspace Variable Key'
    required: false
  variable_value:
    description: 'Workspace Variable Value'
    required: false
  variable_category:
    description: 'Workspace Variable Category'
    required: false
    default: 'terraform'
  variable_sensitive:
    description: 'Workspace Variable Sensitive'
    required: false
    default: 'false'
  variable_hcl:
    description: 'Workspace Variable HCL'
    required: false
    default: 'false'
  variable_description:
    description: 'Workspace Variable Description'
    required: false
    default: 'var_description'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_TF_API_TOKEN: ${{ inputs.tf_api_token }}
    INPUT_TF_WORKSPACE: ${{ inputs.tf_workspace }}
    INPUT_TF_ORGANIZATION: ${{ inputs.tf_organization }}
    INPUT_TF_RUN_TYPE: ${{ inputs.tf_run_type }}

branding:
  icon: 'activity'
  color: 'blue'