name: Test Integration

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-test-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
        TF_ORGANIZATION: ${{ secrets.TF_ORGANIZATION }}
        TF_RUN_TYPE: 'test'

    - name: Terraform API Integration
      uses: monabele/action-integration-terraform-cloud@v0.1.0
      with:
        tf_api_token: ${{ secrets.TF_API_TOKEN }}
        tf_workspace: ${{ secrets.TF_WORKSPACE }}
        tf_organization: ${{ secrets.TF_ORGANIZATION }}
        tf_run_type: 'variable_create'
        tf_variable_key: 'test'
        tf_variable_value: 'test'
        tf_variable_category: 'terraform'
        tf_variable_sensitive: 'false'
        tf_variable_hcl: 'false'
        tf_variable_description: 'test'